version: '3.8'

services:
  mysqldb:
    image: mysql:5.7
    container_name: mysqldb
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=my-secret-pw
      - MYSQL_DATABASE=ProjetPfeAgil
    ports:
      - "3306:3306"
    volumes:
      - db:/var/lib/mysql
    networks:
      - backend

  back:
    depends_on:
      - mysqldb
    build:
      context: ./pfe-project
      dockerfile: Dockerfile.backend
    container_name: back
    restart: unless-stopped
    ports:
      - "3000:80"
    environment:
      - DB_HOST=mysqldb
      - DB_USER=root
      - DB_PASSWORD=my-secret-pw
      - DB_NAME=ProjetPfeAgil
      - DB_PORT=3306
      - CLIENT_ORIGIN=http://localhost:3001
    networks:
      - backend
      - frontend

  front:
    depends_on:
      - back
    build:
      context: ./pffe-project-front
      dockerfile: Dockerfile.frontend
    container_name: front
    ports:
      - "3001:80"
    networks:
      - frontend

volumes:
  db:

networks:
  backend:
    driver: bridge
  frontend:
    driver: bridge
