version: '3.8'

services:
  # Service pour le backend Node.js
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "5000:5000"
    depends_on:
      - mysql
    environment:
      - DB_HOST=mysql
      - DB_USER=root
      - DB_PASSWORD=root_password
      - DB_NAME=ProjetPfeAgil
    networks:
      - app-network

  # Service pour le frontend React.js
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "80:80"
    networks:
      - app-network

  # Service pour MySQL
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: ProjetPfeAgil
    ports:
      - "3306:3306"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge