version: "3.8"

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: backend
    environment:
      - DB_HOST=mysql
      - DB_USER=root
      - DB_PASSWORD=
      - DB_NAME=ProjetPfeAgil
      - NODE_ENV=production
    ports:
      - "3000:3000"
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - myNetwork
    restart: unless-stopped
  mysql:
    image: mysql:8.0.33
    container_name: mysql
    restart: unless-stopped
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: ProjetPfeAgil
      MYSQL_ROOT_HOST: "%"
    command: 
      - --default-authentication-plugin=mysql_native_password
      - --skip-grant-tables
    ports:
      - "3306:3306"
    networks:
      - myNetwork
    volumes:
      - mysql_data:/var/lib/mysql
      - ./database.sql:/docker-entrypoint-initdb.d/database.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
  frontend:
    build:
      context: ../pfe-project-front
      dockerfile: Dockerfile.frontend
    container_name: frontend
    ports:
      - "80:80"
    depends_on:
      backend:
        condition: service_healthy
    networks:
      - myNetwork
    restart: unless-stopped

networks:
  myNetwork:
    driver: bridge
    name: pfe_network

volumes:
  mysql_data:
    name: pfe_mysql_data