version: "3"

services:
  mysql:
    image: mysql:5.7
    container_name: mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ProjetPfeAgil
    ports:
      - "3307:3306"
    networks:
      - myNetworkk
    volumes:
      - mysql_data:/var/lib/mysql
      - ./pfe-project/database.sql:/docker-entrypoint-initdb.d/database.sql

  backend:
    build:
      context: ./pfe-project
      dockerfile: Dockerfile.backend
    ports:
      - "5000:3000"  # Map container port 3000 to host port 5000
    depends_on:
      - mysql
    networks:
      - myNetworkk
    restart: unless-stopped

  frontend:
    build:
      context: ./pffe-project-front
      dockerfile: Dockerfile.frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - myNetworkk
    restart: unless-stopped

networks:
  myNetworkk:
    driver: bridge

volumes:
  mysql_data:
