version: '3.8'

services:
  mysqldb:
    image: mysql:5.7
    container_name: mysqldb
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=my-secret-pw  # Utilisation de variables d'environnement
      - MYSQL_DATABASE=ProjetPfeAgil
    ports:
      - "3306:3306"  # Port local : port docker
    volumes:
      - db:/var/lib/mysql  # Volume persistant pour la base de données
    networks:
      - backend  # Réseau interne pour communication avec le backend

  back:
    depends_on:
      - mysqldb  # Dépend de mysqldb pour que MySQL soit prêt avant
    build:
      context: ./pfe-project  # Répertoire du backend
      dockerfile: Dockerfile.backend
    container_name: back
    restart: unless-stopped
    ports:
      - "3000:3000"  # Port local : port docker
    environment:
      - DB_HOST=mysqldb
      - DB_USER=root
      - DB_PASSWORD=my-secret-pw
      - DB_NAME=ProjetPfeAgil
      - DB_PORT=3306
      - CLIENT_ORIGIN=http://localhost:3001
    networks:
      - backend  # Réseau interne pour communication avec mysqldb
      - frontend  # Réseau pour interagir avec le frontend

  front:
    depends_on:
      - back  # Dépend de bezkoder-api pour être sûr que l'API est prête
    build:
      context: ./pffe-project-front  # Répertoire du frontend
      dockerfile: Dockerfile.frontend
      args:
        - REACT_APP_API_BASE_URL=http://localhost:3000  # URL de l'API
    container_name: front
    ports:
      - "80:80"  # Port local : port docker
    networks:
      - frontend  # Réseau pour interagir avec le frontend

volumes: 
  db:  # Volume persistant pour la base de données MySQL

networks:
  backend:  # Réseau interne pour la communication backend <=> MySQL et backend <=> frontend
  frontend:  # Réseau interne pour la communication frontend <=> backend
