version: "3"

services:
  mysql:
    image: mysql:5.7
    container_name: mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: 
      MYSQL_DATABASE: ProjetPfeAgil
    ports:
      - "3307:3306"
    networks:
      - myNetwork
    volumes:
      - mysql_data:/var/lib/mysql
      - ./pfe-project/database.sql:/docker-entrypoint-initdb.d/database.sql

  backend:
    build:
      context: ./pfe-project
      dockerfile: Dockerfile.backend
    environment:
      - DB_HOST=mysql
      - DB_USER=root
      - DB_PASSWORD=
      - DB_NAME=ProjetPfeAgil
    ports:
      - "5000:3000"
    depends_on:
      - mysql
    networks:
      - myNetwork
    restart: unless-stopped

  frontend:
    build:
      context: ./pfe-project-front
      dockerfile: Dockerfile.frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - myNetwork
    restart: unless-stopped

networks:
  myNetwork:
    driver: bridge

volumes:
  mysql_data:
