FROM node:14

WORKDIR /app
COPY . /app

RUN npm install

# Ajouter le script wait-for-mysql.js
COPY wait-for-mysql.js /app/wait-for-mysql.js

CMD ["sh", "-c", "node wait-for-mysql.js && node server.js"]
