version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: pfe-backend
    ports:
      - "5000:3000"
    environment:
      - NODE_ENV=production
      - DB_HOST=mysql
      - DB_USER=root
      - DB_PASSWORD=root_password
      - DB_NAME=ProjetPfeAgil
    volumes:
      - ./uploads:/usr/src/app/uploads
    restart: always
    depends_on:
      - mysql
    command: ["./wait-for-mysql.sh", "mysql:3306", "--", "npm", "start"]
    networks:
      - pfe-network

  frontend:
    build:
      context: ./pffe-project-front
      dockerfile: Dockerfile.frontend
    container_name: pfe-frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: always
    networks:
      - pfe-network

  mysql:
    image: mysql:8.0
    container_name: pfe-mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root_password
      - MYSQL_DATABASE=ProjetPfeAgil
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - pfe-network

networks:
  pfe-network:
    driver: bridge

volumes:
  mysql_data:
