version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: pfe-backend
    ports:
      - "5000:3000"
    environment:
      - NODE_ENV=production
      - DB_HOST=mysql
      - DB_USER=root
      - DB_PASSWORD=root_password
      - DB_NAME=ProjetPfeAgil
    volumes:
      - ./uploads:/usr/src/app/uploads
    restart: always
    depends_on:
      - mysql
    networks:
      - pfe-network

  frontend:
    build:
      context: ./pffe-project-front
      dockerfile: Dockerfile.frontend
    container_name: pfe-frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: always
    networks:
      - pfe-network

  mysql:
    image: mysql:5.7
    container_name: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root_password
      - MYSQL_DATABASE=ProjetPfeAgil
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - pfe-network
    command: --default-authentication-plugin=mysql_native_password

networks:
  pfe-network:
    driver: bridge

volumes:
  mysql_data:
